
#+TITLE: Heaven & Hell: Portal Edition

#+DESCRIPTION: Design documentation

* Philosophy
  Fast paced hypercasual game where player has no direct control over the protagonist of the game i.e. the Ball.
  This game implements the idea of wormholes or connected points in space or simply portals that
  teleports the ball from one place to another not instantaneously.
  This game includes two dimensions that control the momentum of the ball with the non synchronous passage of time.
  Gravity plays an important part here in controlling the direction of portal openings.
  So this is a game that implements all of space, time and gravity.


* Genre
  Hypercasual Puzzle Physics
  
  
* Targeted Audience
  Players who likes to play fast paced hyper-casual games.


* Targeted Platform
  Web and Mobile OS


* Inspiration
** Heaven and Hell: Original
** Portal Series


* Characters
  The Ball
  

* Game Mechanics
** Gravity
   The gravity of the environment is either normal i.e. downwards or inverted i.e. upwards.
   Gravity alongside its regualar behavioral properties, controls the portal openings.
   Portal openings are always in the direction of the gravity and portal exits are opposite
   to the direction of the gravity. Inverted gravity in the game is expressed using contrast theme.


** Dimension and Space Time Stretching
   There are two separate dimensions in the game, the physical dimension that is visible to the player
   and the portal dimension that exists between the portals.
   In the portal dimension ball continues to freely fall and gain momentum.
   Streching in physical dimension only stretches time.
   Streching in portal dimension only stretches space.


** Space
   Portals creates a link between two points in space. And the teleportation between the portals is
   governed by time. Player can/cannot teleport the ball instantaneously.
   Space between the portals can be stretched which allows player to gain momentum
   even between instantaneous teleportations.
   

** Time
   Players can control the time in the physical dimension only.
   The only time control player has is he can slow down the passage of time.
   This allows player to think and precisely place the portals to have greater control over the game.


* Game Play
  There are two restrictions that makes the game challenging:
** Energy Meter
   Player cannot create portals all the time. After a portal is created the energy bar takes some time to recharge.
   And players cannot create portals until the energy is restored.

   
** Sand Timer
   The sand timer allows player to stretch in a limited amount.
   The timer expires as the player is stretches time or space.
   The timer automatically rechares when player doesn't stretch.
   Recharging definitely takes more time than usage timer.


  And one factor makes the game replayable:
  

** Longer Lifespan
   Player doesn't die instant deaths after he gets hit by obstacle. The game should be more forgiving.
   And so players will have a health bar which decreases after he gets hit. But the game also
   allows to regenerate the lost health through frequent powerups.
   And the game pauses when player is inactive.


* Goal
  The goal of the player is to direct the ball as far as he can without damaging the ball permanently.


* Game Visuals
  Game visuals are attached in the directory.


* Powerups
  Variations of powerups can be created for factorizing energy and sand timer recharges.
  Invincibility and health powerups also must be included.


* Scoring
  Gains score when the player advances forward in the game.
  There can also hard earned in game coins to be used as multipliers.
  We can also have a global leaderboard based on all-time, weekly and daily basis.


* Music and Sound
  Casual fast paced music 
  

* Visual Asthetics
  The game is black and white. When the gravity is downwards i.e. normal then
  background of the game is white and the ball and obstacles is black, and when the
  gravity is inverted the contrast also gets inverted.


* Monetization
  As this is a runner hyper-casual game so monetization is almost the same as all other
  hyper-casual games. Watch advertisement to continue.
  In game coins can also be used to revive when player is down.


* Team
  The development team can be consisted of:
  |------------+--------|
  | Role       | Number |
  |------------+--------|
  | Desginer   |      1 |
  |------------+--------|
  | Programmer |      1 |
  |------------+--------|
  | Artist     |      1 |
  |------------+--------|


* Funding Marketing and Sales
  The game can be published in the official app stores of Android and IOS.
  We can use the native marketing tools available from app stores.
  We can release prototype versions in app stores before releasing and collect
  feedback from gamers to be implemented in the final release.


* Market Analysis
  I still didn't found a game that implements space, time and gravity in a hyper-casual genre and at the same time is also 2D.
  But the game that uses physics and portals to confuse and amaze games to this day is the Portal Series.
** Portal Series
   Both of the portal games are hugely successful. Gamers do find themselves in tricky positions at the start
   but people adapt and amazed at how the puzzles and levels are setup in this game. People finds the physics
   not similar to the real world but very consistent.
   That what makes the game fun, confusing, interesting and worth playing it.

